# Generated by Django 4.2.11 on 2026-04-14 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('up_rate_kbps', models.PositiveIntegerField(default=1024)),
                ('down_rate_kbps', models.PositiveIntegerField(default=1024)),
                ('mikrotik_rate_limit', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_type', models.CharField(choices=[('voucher', 'Voucher'), ('direct', 'Direct'), ('manual', 'Manual')], default='voucher', max_length=16)),
                ('quota_type', models.CharField(choices=[('duration', 'Duration'), ('data', 'Data'), ('duration_and_data', 'Duration And Data'), ('unlimited', 'Unlimited')], default='duration', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('data_bytes', models.BigIntegerField(blank=True, null=True)),
                ('concurrent_device_limit', models.PositiveSmallIntegerField(default=1)),
                ('idle_timeout_seconds', models.PositiveIntegerField(default=600)),
                ('session_timeout_seconds', models.PositiveIntegerField(default=3600)),
                ('is_active', models.BooleanField(default=True)),
                ('speed_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='plans.speedprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
