# Generated by Django — data migration for default GHS unlimited plans

from decimal import Decimal

from django.db import migrations


def create_default_unlimited_plans(apps, schema_editor):
    SpeedProfile = apps.get_model("plans", "SpeedProfile")
    Plan = apps.get_model("plans", "Plan")

    speed, _ = SpeedProfile.objects.get_or_create(
        name="Default Hotspot",
        defaults={
            "up_rate_kbps": 2048,
            "down_rate_kbps": 4096,
            "mikrotik_rate_limit": "2M/4M",
        },
    )

    specs = [
        {
            "name": "1 Day Unlimited",
            "description": "Unlimited data for 24 hours on one device.",
            "price": Decimal("3.00"),
            "duration_minutes": 1440,
            "session_timeout_seconds": 86400,
            "idle_timeout_seconds": 1800,
        },
        {
            "name": "1 Week Unlimited",
            "description": "Unlimited data for 7 days on one device.",
            "price": Decimal("15.00"),
            "duration_minutes": 10080,
            "session_timeout_seconds": 604800,
            "idle_timeout_seconds": 3600,
        },
        {
            "name": "1 Month Unlimited",
            "description": "Unlimited data for 30 days on one device.",
            "price": Decimal("50.00"),
            "duration_minutes": 43200,
            "session_timeout_seconds": 2592000,
            "idle_timeout_seconds": 3600,
        },
    ]

    for row in specs:
        name = row["name"]
        Plan.objects.get_or_create(
            name=name,
            defaults={
                "description": row["description"],
                "price": row["price"],
                "billing_type": "voucher",
                "quota_type": "unlimited",
                "duration_minutes": row["duration_minutes"],
                "data_bytes": None,
                "speed_profile": speed,
                "concurrent_device_limit": 1,
                "idle_timeout_seconds": row["idle_timeout_seconds"],
                "session_timeout_seconds": row["session_timeout_seconds"],
                "is_active": True,
                "is_featured": False,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0003_plan_is_featured"),
    ]

    operations = [
        migrations.RunPython(create_default_unlimited_plans, noop_reverse),
    ]
