# Generated by Django 4.2.11 on 2026-04-14 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NASDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('secret', models.CharField(max_length=128)),
                ('shortname', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['site__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('hotspot_subnet', models.CharField(blank=True, max_length=32)),
                ('management_subnet', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RadiusClient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=80, unique=True)),
                ('shared_secret', models.CharField(max_length=128)),
                ('shortname', models.CharField(blank=True, max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('nas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radius_clients', to='network.nasdevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='nasdevice',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nas_devices', to='network.site'),
        ),
        migrations.AlterUniqueTogether(
            name='nasdevice',
            unique_together={('site', 'ip_address')},
        ),
    ]
