# Generated by Django 4.2.11 on 2026-04-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='code',
        ),
    ]
